name: Python CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox
        cd backend
        pip install -r requirements.txt
    
    - name: Run tests with Nox
      run: |
        cd backend
        nox -s tests
    
    - name: Lint check
      run: |
        cd backend
        nox -s lint
    
    - name: Type checking
      run: |
        cd backend
        nox -s typing
    
    - name: Security scan
      run: |
        cd backend
        nox -s security
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./backend/coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

  docker-build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        cd backend
        docker build -t cheapest-price-finder .
    
    - name: Scan Docker image
      uses: anchore/scan-action@v3
      with:
        image: "cheapest-price-finder:latest"
        fail-build: false

  deployment:
    needs: [test, docker-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to Production
      run: |
        echo "Deploying to production server"
        # ここに本番デプロイメントのスクリプトを追加
        # 例: SSH経由でのデプロイ、クラウドサービスへのデプロイなど
